### PR TITLE
BUG: Remove examples with deprecated classes and update SpatialObject…

### PR DESCRIPTION
**Pull request by fbudin69500**
… examples

Some examples such as `RGBResampleImageFilter.cxx` illustrate deprecated classes
in ITK v5, so these examples were removed.

Examples using Spatial Objects were updated to work with the ITK v5 Spatial
Object API.

Examples using Vector classes that have been integrated in their equivalent
non-vector classes have been updated.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@fbudin69500 Thanks!

**Comment by fbudin69500** [comment]
@hjmjohnson You are welcome. There are a few tests failing but at least everything compiles. The failing tests can be corrected in the near future.

**Comment by hjmjohnson** [comment]
@fbudin69500 I have a student working on migrating all items from WikiExamples to SphinxExamples.  We can fix after the migration is completed.

We are working hard to make a single set of example documentation in order to facilitate maintenance.

**Comment by fbudin69500** [comment]
@hjmjohnson Awesome. Thanks!

**Pull request merged**
