### PR TITLE
BUG: Fix unused variable warning.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix unused variable compiler warning.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@thewtex @fbudin69500 @dzenanz please review and merge if appropriate.

**Comment by dzenanz** [comment]
Is there a mechanism to "push" this code back to the wiki? Or is someone going to copy-paste it manually? Or are we abandoning the wiki examples concept in favor of a versioned git repository?

**Comment by jhlegarreta** [comment]
I can do it for the proposed topics.

I think the thing is that we are still not near from transferring all wiki examples to the Sphinx examples :-S

**Comment by hjmjohnson** [comment]
@jhlegarreta You are the best!  Thank you for taking a lead in documentation for ITK.

**Comment by jhlegarreta** [comment]
@dzenanz @hjmjohnson  @fbudin69500 @thewtex 

Done for
* PR #10: [Wiki example ImageRandomConstIteratorWithIndex](https://itk.org/Wiki/ITK/Examples/Iterators/ImageRandomConstIteratorWithIndex)
* PR #12:  [Wiki example VoronoiDiagram2DGenerator](https://itk.org/Wiki/ITK/Examples/Segmentation/VoronoiDiagram2DGenerator)
* PR #12:  [Wiki example Offset](https://itk.org/Wiki/ITK/Examples/SimpleOperations/Offset)

I also updated the corresponding [ITKCMakeLists](https://itk.org/Wiki/Template:ITKCMakeLists) template to match the current minimum required version for ITK. The change is not yet reflected in the examples, though. I ignore why.

Although I've checked they can be built with versions as low as CMake 3.3(see [VTK minimum requirements](https://gitlab.kitware.com/vtk/vtk/blob/master/CMakeLists.txt) required by the [ITKVtkGlue](C:/SDKs/ITK/itk-head-Bin/lib/cmake/ITK-5.0/Modules/ITKVtkGlue.cmake)), and MSVC 2015, for the sake of consistency with ITK which [requires VERSION 3.9.5](https://github.com/InsightSoftwareConsortium/ITKWikiExamples/blob/master/CMakeLists.txt) across all examples, regardless of whether they use `ITKVtkGlue`, and not being engaged in different versions and all sorts of exotic combinations that we'd be unable to maintain or each file, I've set the `cmake_minimum_required` to **3.9.5**.

I am aware of the fact that the `ITK_Review` flag is no longer present in modern ITK, and thus those lines, although harmless for current ITK master, are no longer required.

**All `CMakeLists.txt` examples** should be updated, concerning both the **required minimum version** and the **flags that no longer make sense for modern ITK**.

But unless users complain about it/report errors, it will not be at the top of my ToDo queue. We do agree it's a huge effort, and it'd be wiser to try to finish the transition to Sphinx, where they could be tested regularly.

Just for info:
* The **tarballs point to** a [repo](https://github.com/lorensen/ITKWikiExamplesTarballs) **owned by Bill**, and hence **this is inconsistent with the current ITK wiki repo**.
* The VTK folks have not updated all their Wiki examples; they've actually *de facto* deprecated them in favor of a GitHub page. @lorensen did a tremendous effort to transition all examples to it. And they even have the examples tested nightly.

So boosting our Sphinx site is still a challenge ahead us. We will do it.

**Comment by lorensen** [comment]
All CMakeLists are defined in wiki templates. If you change the templates
all examples will change.

**Comment by jhlegarreta** [comment]
@lorensen Yes, I did it that way, thanks for pointing Bill: [ITKCMakeLists](https://itk.org/Wiki/Template:ITKCMakeLists), but each example's page seems not being sync'ed. Anyway, as said, the true challenge ahead is to boost the Sphinx examples.

**Comment by lorensen** [comment]
There is also ITKVTKCMakeLists template.

**Pull request merged**
